#ifndef PLUGINS_NORMALESTIMATION_EXPORT_H
#define PLUGINS_NORMALESTIMATION_EXPORT_H
#include <QtGlobal>
#ifdef normalestimator_EXPORTS
#define NE_DLLSPEC Q_DECL_EXPORT
#else
#define NE_DLLSPEC Q_DECL_IMPORT
#endif
#endif  // PLUGINS_NORMALESTIMATION_EXPORT_H
